# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'iosTechRepostitory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '~> 3.1.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'WebViewJavascriptBridge', '~> 6.0'
  pod 'Masonry'
  pod 'ReactiveObjC'



  target 'iosTechRepostitoryTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AFNetworking', '~> 3.1.0'
    pod 'FMDB', '~> 2.7.2'
  end

  target 'iosTechRepostitoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
